version: '3'

services:
  # RabbitMQ
  rabbit:
    hostname: rabbit
    image: rabbitmq:3.7.2
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"  # forward this port because it's useful for debugging
      - "15672:15672"  # here, we can access rabbitmq management plugin
    restart: always

  # Django web server
  web:
    build: .
    command: ./run_web.sh
    volumes:
      - .:/code  # mount current directory inside container
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - rabbit
    restart: always

  # Celery worker
  worker:
    build: .
    command: ./run_celery.sh
    volumes:
      - .:/code
    env_file: .env
    depends_on:
      - rabbit
    restart: always